# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"-\n\nMsg_Header\x12\x0e\n\x06msg_id\x18\x01 \x02(\x07\x12\x0f\n\x07msg_len\x18\x02 \x02(\x07\"+\n\x07\x45xample\x12\x11\n\x06msg_id\x18\x01 \x02(\r:\x01\x30\x12\r\n\x05value\x18\x17 \x02(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MSG_HEADER']._serialized_start=17
  _globals['_MSG_HEADER']._serialized_end=62
  _globals['_EXAMPLE']._serialized_start=64
  _globals['_EXAMPLE']._serialized_end=107
# @@protoc_insertion_point(module_scope)
