/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Msg_ResetPin, Msg_ResetPin, AUTO)


PB_BIND(Msg_ReadPin, Msg_ReadPin, AUTO)


PB_BIND(Msg_PinValue, Msg_PinValue, AUTO)


PB_BIND(Msg_SetPin, Msg_SetPin, AUTO)


PB_BIND(Msg_TogglePin, Msg_TogglePin, AUTO)


PB_BIND(Msg_Header, Msg_Header, AUTO)



